#!/bin/sh

# ----------------------------------------------------------------------------
#  Set the project-specific compilation environment here
#  (if differs from your user environment)
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Set NPP_DIR as a project directory so that $NPP_DIR/src/npp_app.h can be found

#export NPP_DIR=


# ----------------------------------------------------------------------------
# Set include path (might be required for OpenSSL and MySQL)
# Example: export CPATH=/usr/include;/usr/include/mysql

#export CPATH=


# ----------------------------------------------------------------------------
# Set library path (might be required for OpenSSL and MySQL)
# Example: export LIBRARY_PATH=/usr/lib/openssl;/usr/lib/mysql

#export LIBRARY_PATH=


# ----------------------------------------------------------------------------
# Set additional APP modules

#export NPP_APP_MODULES=


# ----------------------------------------------------------------------------
# Set additional SVC modules

#export NPP_SVC_MODULES=


# ----------------------------------------------------------------------------
# Call the main making script (don't change this)

./make_npp
