#!/bin/sh


echo Making npp_app...

g++ npp_app.cpp \
../lib/npp_eng.c ../lib/npp_lib.c ../lib/npp_usr.c \
-D NPP_APP \
-I. -I../lib \
-lrt -lz -lcrypto -lssl \
-s -O3 \
-o ../bin/npp_app


if [ $? -eq 0 ]
then
    echo Making npp_svc...

    g++ npp_svc.cpp \
    ../lib/npp_eng.c ../lib/npp_lib.c ../lib/npp_usr.c \
    -D NPP_SVC \
    -I. -I../lib \
    -lrt \
    -s -O3 \
    -o ../bin/npp_svc
fi


if [ $? -eq 0 ]
then
    echo Making npp_watcher...

    gcc ../lib/npp_watcher.c \
    ../lib/npp_lib.c \
    -D NPP_WATCHER \
    -I. -I../lib \
    -s -O3 \
    -o ../bin/npp_watcher
fi
